<div class="wrap">
    <h2>Settings</h2>
    <form method="post" action="<?= filter_input(INPUT_SERVER, 'REQUEST_URI') ?>">
        <input type="hidden" id="update_options" name="update_options" value="true">
        <table class="form-table">            
            <tr valign="top">     
                <th scope="row">Optimize Admin?</th>
                <td>
                    <input type="radio" id="OptimizeAdmin" name="OptimizeAdmin" <?= esc_attr(get_option('OptimizeAdmin')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="OptimizeAdmin" name="OptimizeAdmin" <?= esc_attr(get_option('OptimizeAdmin')) ? '' : 'checked="checked"'; ?> value="0" />No
                </td>
            </tr>
            <tr valign="top">     
                <th scope="row">Use Static Cache?</th>
                <td>
                    <input type="radio" id="StaticCache" name="StaticCache" <?= esc_attr(get_option('StaticCache')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="StaticCache" name="StaticCache" <?= esc_attr(get_option('StaticCache')) ? '' : 'checked="checked"'; ?> value="0" />No
                </td>
            </tr>            
            <tr valign="top">
                <th scope="row">Static Cache Dir :</th>
                <td>
                    <input type="text" name="StaticCacheDir" value="<?php echo esc_attr(get_option('StaticCacheDir')); ?>" />
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">App Environment:</th>
                <td>                    
                    <input type="radio" id="APP_ENV" name="APP_ENV" <?= (esc_attr(get_option('APP_ENV')) == 'production') ? 'checked="checked"' : ''; ?> value="production" />Production
                    <input type="radio" id="APP_ENV" name="APP_ENV" <?= (esc_attr(get_option('APP_ENV')) == 'production') ? '' : 'checked="checked"'; ?> value="development" />Development
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">Charset:</th>
                <td>
                    <input type="text" name="charset" value="<?php echo esc_attr(get_option('charset')); ?>" />
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">Remove Meta Charset?</th>
                <td>
                    <input type="radio" id="RemoveMetaCharset" name="RemoveMetaCharset" <?= esc_attr(get_option('RemoveMetaCharset')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="RemoveMetaCharset" name="RemoveMetaCharset" <?= esc_attr(get_option('RemoveMetaCharset')) ? '' : 'checked="checked"'; ?> value="0" />No                    
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">URI Base Path:</th>
                <td>
                    <input type="text" name="URIBasePath" value="<?php echo esc_attr(get_option('URIBasePath')); ?>" />
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">Base Path:</th>
                <td>
                    <input type="text" name="BasePath" value="<?php echo esc_attr(get_option('BasePath')); ?>" />
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">Public Cache Dir:</th>
                <td>
                    <input type="text" name="PublicCacheDir" value="<?php echo esc_attr(get_option('PublicCacheDir')); ?>" />
                </td>
            </tr>                                    
            <tr valign="top">
                <th scope="row">LazyLoad:</th>
                <td>
                    <input type="radio" id="LazyLoadImages" name="LazyLoadImages" <?= esc_attr(get_option('LazyLoadImages')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="LazyLoadImages" name="LazyLoadImages" <?= esc_attr(get_option('LazyLoadImages')) ? '' : 'checked="checked"'; ?> value="0" />No                    
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">Lazy Load Base Path:</th>
                <td>
                    <input type="text" name="LazyLoadBasePath" value="<?php echo esc_attr(get_option('LazyLoadBasePath')); ?>" />
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">Lazy Load Place Holder:</th>
                <td>
                    <input type="text" name="LazyLoadPlaceHolder" value="<?php echo esc_attr(get_option('LazyLoadPlaceHolder')); ?>" />
                </td>
            </tr>               
            <tr valign="top">
                <th scope="row">Async All Js?</th>
                <td>                    
                    <input type="radio" id="JsAllAsync" name="JsAllAsync" <?= esc_attr(get_option('JsAllAsync')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="JsAllAsync" name="JsAllAsync" <?= esc_attr(get_option('JsAllAsync')) ? '' : 'checked="checked"'; ?> value="0" />No
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">Integrate All Inline Javascript?</th>
                <td>                    
                    <input type="radio" id="JavascriptIntegrateInline" name="JavascriptIntegrateInline" <?= esc_attr(get_option('JavascriptIntegrateInline')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="JavascriptIntegrateInline" name="JavascriptIntegrateInline" <?= esc_attr(get_option('JavascriptIntegrateInline')) ? '' : 'checked="checked"'; ?> value="0" />No
                </td>
            </tr>            
            <tr valign="top">
                <th scope="row">Move All Javascript to Footer?</th>
                <td>
                    <input type="radio" id="JavascriptOnFooter" name="JavascriptOnFooter" <?= esc_attr(get_option('JavascriptOnFooter')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="JavascriptOnFooter" name="JavascriptOnFooter" <?= esc_attr(get_option('JavascriptOnFooter')) ? '' : 'checked="checked"'; ?> value="0" />No                                        
                </td>
            </tr>                                
            <tr valign="top">
                <th scope="row">Integrate All Javascript?</th>
                <td>                    
                    <input type="radio" id="JavascriptIntegrate" name="JavascriptIntegrate" <?= esc_attr(get_option('JavascriptIntegrate')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="JavascriptIntegrate" name="JavascriptIntegrate" <?= esc_attr(get_option('JavascriptIntegrate')) ? '' : 'checked="checked"'; ?> value="0" />No                                        
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">Minify All Css?</th>
                <td>                    
                    <input type="radio" id="CssMinify" name="CssMinify" <?= esc_attr(get_option('CssMinify')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="CssMinify" name="CssMinify" <?= esc_attr(get_option('CssMinify')) ? '' : 'checked="checked"'; ?> value="0" />No                                                            
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">Integrate All CSS Inline?</th>
                <td>                    
                    <input type="radio" id="CssIntegrateInline" name="CssIntegrateInline" <?= esc_attr(get_option('CssIntegrateInline')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="CssIntegrateInline" name="CssIntegrateInline" <?= esc_attr(get_option('CssIntegrateInline')) ? '' : 'checked="checked"'; ?> value="0" />No                                                            
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">Integrate All Css?</th>
                <td>                    
                    <input type="radio" id="CssMinify" name="CssIntegrate" <?= esc_attr(get_option('CssIntegrate')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="CssMinify" name="CssIntegrate" <?= esc_attr(get_option('CssIntegrate')) ? '' : 'checked="checked"'; ?> value="0" />No                                                            
                </td>
            </tr>            
            <tr valign="top">
                <th scope="row">Css Spritify?</th>
                <td>                    
                    <input type="radio" id="CssSpritify" name="CssSpritify" <?= esc_attr(get_option('CssSpritify')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="CssSpritify" name="CssSpritify" <?= esc_attr(get_option('CssSpritify')) ? '' : 'checked="checked"'; ?> value="0" />No
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">Separate CSS Inline?</th>
                <td>                    
                    <input type="radio" id="CSSSeparateInline" name="CSSSeparateInline" <?= esc_attr(get_option('CSSSeparateInline')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="CSSSeparateInline" name="CSSSeparateInline" <?= esc_attr(get_option('CSSSeparateInline')) ? '' : 'checked="checked"'; ?> value="0" />No
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">CookieLess Domain:</th>
                <td>
                    <input type="text" name="CookieLessDomain" value="<?php echo esc_attr(get_site_option('CookieLessDomain')); ?>" />
                </td>
            </tr>                        
        </table>
        <?php submit_button(); ?>
    </form>
</div>